Application/OnlineBloodDonationWebsite/BloodDonationWebapp/Controllers/AccountsController.cs
using BloodDonationWebapp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DatabaseLayer;

namespace BloodDonationWebapp.Controllers
{
    public class AccountsController : Controller
    {
        OnlineBloodDonation_DbEntities DB = new OnlineBloodDonation_DbEntities();
        public ActionResult AllNewUserRequest()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var users = DB.UserTables.Where(u => u.AccountStatusID == 1).ToList();
            return View(users);
        }
        public ActionResult UserDetails(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var user = DB.UserTables.Find(id);
            return View(user);
        }
        public ActionResult UserApproved(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var user = DB.UserTables.Find(id);
            user.AccountStatusID = 2;
            DB.Entry(user).State = System.Data.Entity.EntityState.Modified;
            DB.SaveChanges();
            return RedirectToAction("AllNewUserRequest");
        }
        public ActionResult UserRejected(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var user = DB.UserTables.Find(id);
            user.AccountStatusID = 3;
            DB.Entry(user).State = System.Data.Entity.EntityState.Modified;
            DB.SaveChanges();
            return RedirectToAction("AllNewUserRequest");
        }
        public ActionResult AddNewDonorByBloodBank()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var collectbloodMV = new CollectBloodMV();
            ViewBag.CityID = new SelectList(DB.CityTables.ToList(), "CityID", "City", "0");
            ViewBag.BloodGroupID = new SelectList(DB.BloodGroupsTables.ToList(), "BloodGroupID", "BloodGroup", "0");
            ViewBag.GenderID = new SelectList(DB.GenderTables.ToList(), "GenderID", "Gender", "0");
            return View(collectbloodMV);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNewDonorByBloodBank(CollectBloodMV collectBloodMV)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int bloodbankID = 0;
            string bloodbankid = Convert.ToString(Session["BloodBankID"]);
            int.TryParse(bloodbankid, out bloodbankID);
            var currentdate=DateTime.Now;
            var currentcampaign = DB.CampaignTables.Where(c => c.CampaignDate == currentdate && c.BloodBankID == bloodbankID).FirstOrDefault();
            
            if (ModelState.IsValid)
            {
                using (var transaction = DB.Database.BeginTransaction())
                {
                    try
                    {
                        var checkdonor = DB.DonorTables.Where(d => d.AadharNo.Trim().Replace("-", "") == collectBloodMV.DonorDetails.AadharNo.Trim().Replace("-", "")).FirstOrDefault();
                        if (checkdonor == null)
                        {
                            var user = new UserTable();
                            user.UserName = collectBloodMV.DonorDetails.FullName.Trim();
                            user.EmailAddress = collectBloodMV.DonorDetails.EmailAddress;
                            user.Password = "12345";
                            user.AccountStatusID = 2;
                            user.UserTypeID = 2;
                            user.Description = "Add By Blood Bank";
                            DB.UserTables.Add(user);
                            DB.SaveChanges();

                            var donor = new DonorTable();
                            donor.FullName = collectBloodMV.DonorDetails.FullName;
                            donor.BloodGroupID = collectBloodMV.BloodGroupID;
                            donor.Location = collectBloodMV.DonorDetails.Location;
                            donor.ContactNo = collectBloodMV.DonorDetails.ContactNo;
                            donor.LastDonationDate = DateTime.Now;
                            donor.AadharNo = collectBloodMV.DonorDetails.AadharNo;
                            donor.GenderID = collectBloodMV.GenderID;
                            donor.CityID = collectBloodMV.CityID;
                            donor.UserID = user.UserID;
                            DB.DonorTables.Add(donor);
                            DB.SaveChanges();
                            checkdonor = DB.DonorTables.Where(d => d.AadharNo.Trim().Replace("-", "") == collectBloodMV.DonorDetails.AadharNo.Trim().Replace("-", "")).FirstOrDefault();
                        }

                        if ((DateTime.Now - checkdonor.LastDonationDate).TotalDays < 120)
                        {
                            ModelState.AddModelError(string.Empty, "Donor has already donated blood in last 120 Days!");
                            transaction.Rollback();
                        }
                        else
                        {

                            var checkbloodgroupstock = DB.BloodStockTables.Where(s => s.BloodBankID == bloodbankID && s.BloodBankID == collectBloodMV.BloodGroupID).FirstOrDefault();
                            if (checkbloodgroupstock == null)
                            {
                                var bloodbankstock = new BloodStockTable();
                                bloodbankstock.BloodGroupID = collectBloodMV.BloodGroupID;
                                bloodbankstock.BloodBankID = bloodbankID;
                                bloodbankstock.Quantity = 0;
                                bloodbankstock.Status = true;
                                bloodbankstock.Description = "";
                                DB.BloodStockTables.Add(bloodbankstock);
                                DB.SaveChanges();
                                checkbloodgroupstock = DB.BloodStockTables.Where(s => s.BloodBankID == bloodbankID && s.BloodBankID == collectBloodMV.BloodGroupID).FirstOrDefault();
                            }
                            var collectedblooddetails = new BloodStockDetailTable();
                            
                                checkbloodgroupstock.Quantity += collectBloodMV.Quantity;
                                DB.Entry(checkbloodgroupstock).State = System.Data.Entity.EntityState.Modified;
                                DB.SaveChanges();
                                collectedblooddetails.BloodBankStockID = checkbloodgroupstock.BloodBankStockID;
                           
                            
                            
                            collectedblooddetails.BloodGroupID = collectBloodMV.BloodGroupID;
                           
                                collectedblooddetails.CampaignID = currentcampaign.CampaignID;
                           
                            collectedblooddetails.Quantity = collectBloodMV.Quantity;
                            
                                collectedblooddetails.DonorID = checkdonor.DonorID;
                            collectedblooddetails.DonationDate = DateTime.Now;
                            DB.BloodStockDetailTables.Add(collectedblooddetails);
                            DB.SaveChanges();

                            checkdonor.LastDonationDate = DateTime.Now;
                            DB.Entry(checkdonor).State = System.Data.Entity.EntityState.Modified;
                            DB.SaveChanges();
                            transaction.Commit();
                            return RedirectToAction("BloodBankStock", "BloodBank");
                        }
                    }
                    catch
                    {
                        ModelState.AddModelError(string.Empty, "Please Provide The Correct Information!");
                        transaction.Rollback();
                    }

                }

            }
            else
            {
                ModelState.AddModelError(string.Empty, "Please Provide Donor's Compelete Information!");
            }
            ViewBag.CityID = new SelectList(DB.CityTables.ToList(), "CityID", "City", collectBloodMV.CityID);
            ViewBag.BloodGroupID = new SelectList(DB.BloodGroupsTables.ToList(), "BloodGroupID", "BloodGroup", collectBloodMV.BloodGroupID);
            ViewBag.GenderID = new SelectList(DB.GenderTables.ToList(), "GenderID", "Gender", collectBloodMV.GenderID);

            return View(collectBloodMV);
        }
    }
}

Application/OnlineBloodDonationWebsite/BloodDonationWebapp/Views/Accounts/AddNewDonorByBloodBank.cshtml
@model BloodDonationWebapp.Models.CollectBloodMV
@{
    ViewBag.Title = "Collect Blood";
}

@{
    <style>
        dt {
            float: left;
            clear: left;
            width: 8em;
        }

        dd {
            margin: 0 0 0 9em;
            padding: 0 0 2.5em 0;
        }
    </style>
    <div class="col-md-12">
        <div class="contact-form-block">
            <h2 class="contact-title"> Enter Collected Blood Details </h2>
            <div>
                
                <div class="row">
                    @using (Html.BeginForm("AddNewDonorByBloodBank", "Accounts", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        //@Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <h4>Enter Donor Details</h4>
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                    Full Name:
                                </dt>
                                <dd>
                                    @Html.EditorFor(model => model.DonorDetails.FullName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DonorDetails.FullName, "", new { @class = "text-danger" })
                                </dd>
                                <dt>
                                    Email Address:
                                </dt>
                                <dd>
                                    @Html.EditorFor(model => model.DonorDetails.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DonorDetails.EmailAddress, "", new { @class = "text-danger" })
                                </dd>

                                <dt>
                                    Address:
                                </dt>
                                <dd>
                                    @Html.EditorFor(model => model.DonorDetails.Location, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DonorDetails.Location, "", new { @class = "text-danger" })
                                </dd>
                                <dt>
                                    City:
                                </dt>
                                <dd>
                                    <div class="select-style">

                                        @Html.DropDownList("CityID", null, "--Your City--", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
                                    </div>
                                </dd>


                                <dt>
                                    Aadhar Number:
                                </dt>
                                <dd>
                                    @Html.EditorFor(model => model.DonorDetails.AadharNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DonorDetails.AadharNo, "", new { @class = "text-danger" })
                                </dd>
                                <dt>
                                    Gender:
                                </dt>
                                <dd>
                                    <div class="select-style">

                                        @Html.DropDownList("GenderID", null, "--Select Gender--", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.GenderID, "", new { @class = "text-danger" })
                                    </div>
                                </dd>
                                <dt>
                                    Contact Number:
                                </dt>
                                <dd>
                                    @Html.EditorFor(model => model.DonorDetails.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DonorDetails.ContactNo, "", new { @class = "text-danger" })
                                </dd>
                            </dl>
                            <hr />
                        </div>
                        <div class="col-md-6">
                            <h4>Enter Stock Details</h4>
                            <dl class="dl-horizontal">
                                <hr />

                                <dt>
                                    Blood Group:
                                </dt>
                                <dd>
                                    <div class="select-style">

                                        @Html.DropDownList("BloodGroupID", null, "--Select Blood Group--", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.BloodGroupID, "", new { @class = "text-danger" })
                                    </div>
                                </dd>
                                <dt>
                                    Blood Quantity:
                                </dt>
                                <dd>
                                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                </dd>
                                <dt>

                                </dt>
                                <dd>
                                    <br />
                                    <br />
                                    <div class="row">
                                        <div class="col-md-8" align="right">
                                            <input type="submit" value="SUBMIT" class="btn btn-theme" />
                                        </div>
                                    </div>
                                </dd>
                            </dl>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

Application/OnlineBloodDonationWebsite/BloodDonationWebapp/Views/Accounts/AllNewUserRequest.cshtml
@model IEnumerable<DatabaseLayer.UserTable>

@{
    ViewBag.Title = "AllNewUserRequest";
}
<div class="col-md-12">
 <div class="contact-form-block">
<h2 class="contact-title">All New User Requests</h2>

     
        <table class="table table-hover">
            <tr>
                <th>
                    Relationship
                </th>
                <th>
                    User Name
                </th>
                <th>
                    Email Address
                </th>
                <th>
                    Description
                </th>
                <th>
                    Account Status
                </th>

                <th>
                    Action
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserTypeTable.UseType)
                    </td>
                    <td>
                        @Html.ActionLink(item.UserName,"UserDetails",new {id=item.UserID}) 
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EmailAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AccountStatusTable.AccountStatus)
                    </td>

                    <td>
                        @Html.ActionLink("Approved", "UserApproved", new { id = item.UserID }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Rejected", "UserRejected", new { id = item.UserID }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }

        </table>
     </div>
    </div>

Application/OnlineBloodDonationWebsite/BloodDonationWebapp/Views/Accounts/UserDetails.cshtml
@model DatabaseLayer.UserTable

@{
    ViewBag.Title = "User Details";
}

<div class="col-md-12">
    <div class="contact-form-block">
        <h2 class="contact-title">Request User Details</h2>

        <div>
            <hr />
            <h4>User Information</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    User Name:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserName)
                </dd>

                <dt>
                    Email Address:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EmailAddress)
                </dd>


                <dt>
                    Description:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    Account Status:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AccountStatusTable.AccountStatus)
                </dd>

                <dt>
                    Relationship:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserTypeTable.UseType)
                </dd>

            </dl>
            <hr />
            @{

                if (Model.HospitalTables.Count() > 0)
                {
                    foreach (var hospital in Model.HospitalTables)

                    {
                        <hr />
                        <h4>Hospital Information</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                Hospital Name:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => hospital.FullName)
                            </dd>
                            <dt>
                                Contact Number:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => hospital.PhoneNo)
                            </dd>
                            <dt>
                                Email Address:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => hospital.Email)
                            </dd>
                            <dt>
                                Website:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => hospital.Website)
                            </dd>
                            <dt>
                                Address:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => hospital.Address)
                            </dd>
                            <dt>
                                City:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => hospital.CityTable.City)
                            </dd>
                        </dl>
                    }
                }
                else if (Model.BloodBankTables.Count > 0)
                {
                    foreach (var bloodbank in Model.BloodBankTables)
                    {
                        <hr />
                        <h4>BloodBank Information</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                Full Name:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => bloodbank.BloodBankName)
                            </dd>
                            <dt>
                                Address:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => bloodbank.Address)
                            </dd>
                            <dt>
                                Landmark:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => bloodbank.Location)
                            </dd>
                            <dt>
                                City:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => bloodbank.CityTable.City)
                            </dd>
                            <dt>
                                Email Address:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => bloodbank.Email)
                            </dd>
                            <dt>
                                Website:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => bloodbank.Website)
                            </dd>
                            <dt>
                                Contact Number:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => bloodbank.PhoneNo)
                            </dd>
                        </dl>
                    }
                }
                else if (Model.DonorTables.Count > 0)
                {
                    foreach (var donor in Model.DonorTables)
                    {
                        <hr />
                        <h4>Donor Information</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                Full Name:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.FullName)
                            </dd>
                            <dt>
                                Address:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.Location)
                            </dd>
                            <dt>
                                City:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.CityTable.City)
                            </dd>
                            <dt>
                                Blood Group:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.BloodGroupsTable.BloodGroup)
                            </dd>

                            <dt>
                                Aadhar Number:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.AadharNo)
                            </dd>
                            <dt>
                                Gender:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.GenderTable.Gender)
                            </dd>
                            <dt>
                                Donation Date:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.LastDonationDate)
                            </dd>
                            <dt>
                                Contact Number:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => donor.ContactNo)
                            </dd>
                        </dl>
                    }
                }
                else if (Model.SeekerTables.Count > 0)
                {
                    foreach (var seeker in Model.SeekerTables)
                    {
                        <hr />
                        <h4>Seeker Information</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                Full Name:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.FullName)
                            </dd>
                            <dt>
                                Age:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.Age)
                            </dd>
                            <dt>
                                Address:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.Address)
                            </dd>
                            <dt>
                                City:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.CityTable.City)
                            </dd>
                            <dt>
                                Blood Group:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.BloodGroupsTable.BloodGroup)
                            </dd>

                            <dt>
                                Aadhar Number:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.AadharNo)
                            </dd>
                            <dt>
                                Gender:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.GenderTable.Gender)
                            </dd>
                            <dt>
                                Contact Number:
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => seeker.ContactNo)
                            </dd>
                        </dl>
                    }
                }
            }

        </div>
        <p>
            @Html.ActionLink("Approved", "UserApproved", new { id = Model.UserID }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Rejected", "UserRjected", new { id = Model.UserID }, new { @class = "btn btn-danger" })
        </p>
        </div>
</div>